# Generated by Django 3.1.1 on 2020-10-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
